#- path: /srv/salt/nginx/nginx.conf
#  defer: true
#  permissions: '0644'
#  owner: salt:salt
#  encoding: b64
#  content: >
#    dXNlciAgd3d3LWRhdGE7Cndvcmtlcl9wcm9jZXNzZXMgIGF1dG87CgplcnJvcl9sb2cgIC92YXIv
#    bG9nL25naW54L2Vycm9yLmxvZyBub3RpY2U7CnBpZCAgICAgICAgL3Zhci9ydW4vbmdpbngucGlk
#    OwoKZXZlbnRzIHsKICAgIHdvcmtlcl9jb25uZWN0aW9ucyAgMTAyNDsKfQoKaHR0cCB7CiAgICBp
#    bmNsdWRlICAgICAgIC9ldGMvbmdpbngvbWltZS50eXBlczsKICAgIGRlZmF1bHRfdHlwZSAgYXBw
#    bGljYXRpb24vb2N0ZXQtc3RyZWFtOwoKICAgIGxvZ19mb3JtYXQganNvbiBlc2NhcGU9anNvbiAn
#    eyJyZW1vdGVfYWRkciI6IiRyZW1vdGVfYWRkciIsICJyZW1vdGVfdXNlciI6IiRyZW1vdGVfdXNl
#    ciIsICJ0aW1lX2xvY2FsIjoiJHRpbWVfbG9jYWwiLCAicmVxdWVzdCI6IiRyZXF1ZXN0IiwgJwog
#    ICAgICAgICAgICAgICAnInN0YXR1cyI6IiRzdGF0dXMiLCAiYm9keV9ieXRlc19zZW50IjoiJGJv
#    ZHlfYnl0ZXNfc2VudCIsICJodHRwX3JlZmVyZXIiOiIkaHR0cF9yZWZlcmVyIiwgImh0dHBfdXNl
#    cl9hZ2VudCI6IiRodHRwX3VzZXJfYWdlbnQiLCAnCiAgICAgICAgICAgICAgICAgICAgICAgICAn
#    Imhvc3QiOiIkaG9zdCIsICJyZXF1ZXN0X3RpbWUiOiIkcmVxdWVzdF90aW1lIiwgInJlcXVlc3Rf
#    bGVuZ3RoIjoiJHJlcXVlc3RfbGVuZ3RoIiwgInVwc3RyZWFtX2FkZHIiOiIkdXBzdHJlYW1fYWRk
#    ciIsICcKICAgICAgICAgICAgICAgICAgICAgJyJ1cHN0cmVhbV9yZXNwb25zZV90aW1lIjoiJHVw
#    c3RyZWFtX3Jlc3BvbnNlX3RpbWUiLCAidXBzdHJlYW1fc3RhdHVzIjoiJHVwc3RyZWFtX3N0YXR1
#    cyIsICJyZWFsaXBfcmVtb3RlX2FkZHIiOiIkcmVhbGlwX3JlbW90ZV9hZGRyIn0nOwoKICAgIGxv
#    Z19mb3JtYXQgbWFpbiAnJHJlbW90ZV9hZGRyIC0gJHJlbW90ZV91c2VyIFskdGltZV9sb2NhbF0g
#    JwogICAgICAgICAgICAgICAgICAnIiRyZXF1ZXN0IiAkc3RhdHVzICRib2R5X2J5dGVzX3NlbnQg
#    JwogICAgICAgICAgICAgICAgICAnIiRodHRwX3JlZmVyZXIiICIkaHR0cF91c2VyX2FnZW50IiAn
#    CiAgICAgICAgICAgICAgICAgICdob3N0PSRob3N0IHJlcXVlc3RfdGltZT0kcmVxdWVzdF90aW1l
#    IHJlcXVlc3RfbGVuZ3RoPSRyZXF1ZXN0X2xlbmd0aCAnCiAgICAgICAgICAgICAgICAgICd1cHN0
#    cmVhbV9hZGRyPSR1cHN0cmVhbV9hZGRyIHVwc3RyZWFtX3Jlc3BvbnNlX3RpbWU9JHVwc3RyZWFt
#    X3Jlc3BvbnNlX3RpbWUgJwogICAgICAgICAgICAgICAgICAndXBzdHJlYW1fc3RhdHVzPSR1cHN0
#    cmVhbV9zdGF0dXMgcmVhbGlwX3JlbW90ZV9hZGRyPSRyZWFsaXBfcmVtb3RlX2FkZHInOwoKICAg
#    IGFjY2Vzc19sb2cgIC92YXIvbG9nL25naW54L2FjY2Vzcy5sb2cganNvbjsKCiAgICBzZW5kZmls
#    ZSAgICAgICAgb247CiAgICAjdGNwX25vcHVzaCAgICAgb247CgogICAga2VlcGFsaXZlX3RpbWVv
#    dXQgIDY1OwoKICAgICNnemlwICBvbjsKCiAgICBtYXAgJHJlcXVlc3RfbWV0aG9kICRibG9jayB7
#    CiAgICAgIGRlZmF1bHQgIjAiOwogICAgICAiR0VUIiAiMSI7CiAgICB9CgogICAgaW5jbHVkZSAv
#    ZXRjL25naW54L2NvbmYuZC8qLmNvbmY7Cn0K    
#- path: /srv/salt/top.sls
#  defer: true
#  permissions: '0644'
#  owner: salt:salt
#  content: |
#    base:
#      'lb*':
#      - nginx
#      - upstreams
#      'app*':
#      - nginx
#      - wordpress
#      'db*':
#      - database
#- path: /srv/salt/nginx/init.sls
#  defer: true
#  permissions: '0644'
#  owner: salt:salt
#  content: |
#    nginx:
#      pkg.installed:
#      - name: nginx
#      - refresh: true
#      service.running:
#      - enable: True
#      - require:
#        - pkg: nginx  
#      - watch:
#        - file: /etc/nginx/nginx.conf
#    /etc/nginx/nginx.conf:
#      file.managed:
#      - source: salt://nginx/nginx.conf
#      - user: www-data
#      - group: www-data
#      - mode: 644
#      - require:
#        - pkg: nginx
# 
#- path: /srv/salt/upstreams.sls
#  defer: true
#  permissions: "0644"
#  owner: salt:salt
#  content: |
#    /etc/nginx/conf.d/lb.conf:
#      file.managed:
#        - source: salt://upstreams.conf
#        - user: www-data
#        - group: www-data
#        - mode: 644
#        - template: jinja
#        - require:
#          - pkg: nginx
#        - watch_in:
#          - service: nginx
#- path: /srv/salt/upstreams.conf
#  defer: true
#  permissions: "0644"
#  owner: salt:salt
#  encoding: b64
#  content: >
#    eyUgc2V0IG1pbmlvbl9pcHMgPSBzYWx0WydtaW5lLmdldCddKHRndD0nYXBwKicsIGZ1bj0nbmV0
#    d29yay5pcF9hZGRycycpIC0lfQp1cHN0cmVhbSBAd29yZHByZXNzIHsKeyUtIGZvciBob3N0IGlu
#    IG1pbmlvbl9pcHMgJX0KeyUtIGZvciBpcCBpbiBtaW5pb25faXBzW2hvc3RdICV9CiAgc2VydmVy
#    ICB7eyBpcCB9fTo4MCBtYXhfZmFpbHM9MTsKeyUtIGVuZGZvciAlfQp7JS0gZW5kZm9yICV9Cn0K
#    CnNlcnZlciB7CiAgbGlzdGVuIDgwOwogIHNlcnZlcl9uYW1lIF87CgogIGxvY2F0aW9uIC8gewog
#    ICAgcHJveHlfcGFzcyBodHRwOi8vQHdvcmRwcmVzczsKICAgIHByb3h5X3NldF9oZWFkZXIgWC1S
#    ZWFsLUlQICRyZW1vdGVfYWRkcjsKICAgIHByb3h5X3NldF9oZWFkZXIgWC1Gb3J3YXJkZWQtRm9y
#    ICRyZW1vdGVfYWRkcjsKICAgIHByb3h5X3NldF9oZWFkZXIgSG9zdCAkaG9zdDsKICAgIHByb3h5
#    X2Nvbm5lY3RfdGltZW91dCA1OwogIH0KfQo=
#- path: /srv/salt/wordpress/init.sls
#  defer: true
#  permissions: "0644"
#  owner: salt:salt
#  content: |
#    wordpress:
#      pkg.installed:
#      - name: php-fpm
#      - pkgs:
#        - php-fpm
#        - php-mysql
#        - unzip
#      - refresh: true
#
#      service.running:
#      - name: php8.1-fpm
#      - enable: true
#      - require:
#        - pkg: php-fpm
#      - watch:
#        - file: /etc/php/8.1/fpm/php.ini
#
#      file.replace:
#      - name: "/etc/php/8.1/fpm/php.ini"
#      - pattern: "^[;]*cgi.fix_pathinfo.*"
#      - repl: "cgi.fix_pathinfo=0"
#
#    /etc/nginx/conf.d/wp.conf:
#      file.managed:
#      - source: salt://wordpress/wp.conf
#      - user: www-data
#      - group: www-data
#      - mode: 644
#      - require:
#        - pkg: nginx
#      - watch_in:
#        - service: nginx
#    
#    /var/www:
#      archive.extracted:
#      - source: https://wordpress.org/latest.zip
#      - user: www-data
#      - group: www-data
#      - use_etag: true
#
#    /var/www/wordpress/wp-config.php:
#      file.managed:
#      - source: salt://wordpress/wp-config.php
#      - user: www-data
#      - group: www-data
#      - mode: 644
#      - template: jinja
#      - require:
#        - archive: /var/www        
#
#- path: /srv/salt/wordpress/wp.conf
#  defer: true
#  permissions: "0644"
#  owner: salt:salt
#  encoding: b64
#  content: >
#    IyBVcHN0cmVhbSB0byBhYnN0cmFjdCBiYWNrZW5kIGNvbm5lY3Rpb24ocykgZm9yIHBocAp1cHN0
#    cmVhbSBwaHAgewogICAgICAgIHNlcnZlciB1bml4Oi9ydW4vcGhwL3BocDguMS1mcG0uc29jazsK
#    fQoKc2VydmVyIHsKICAgICAgICAjIyBZb3VyIHdlYnNpdGUgbmFtZSBnb2VzIGhlcmUuCiAgICAg
#    ICAgc2VydmVyX25hbWUgXzsKICAgICAgICAjIyBZb3VyIG9ubHkgcGF0aCByZWZlcmVuY2UuCiAg
#    ICAgICAgcm9vdCAvdmFyL3d3dy93b3JkcHJlc3M7CiAgICAgICAgIyMgVGhpcyBzaG91bGQgYmUg
#    aW4geW91ciBodHRwIGJsb2NrIGFuZCBpZiBpdCBpcywgaXQncyBub3QgbmVlZGVkIGhlcmUuCiAg
#    ICAgICAgaW5kZXggaW5kZXgucGhwOwoKICAgICAgICBsb2NhdGlvbiA9IC9mYXZpY29uLmljbyB7
#    CiAgICAgICAgICAgICAgICBsb2dfbm90X2ZvdW5kIG9mZjsKICAgICAgICAgICAgICAgIGFjY2Vz
#    c19sb2cgb2ZmOwogICAgICAgIH0KCiAgICAgICAgbG9jYXRpb24gPSAvcm9ib3RzLnR4dCB7CiAg
#    ICAgICAgICAgICAgICBhbGxvdyBhbGw7CiAgICAgICAgICAgICAgICBsb2dfbm90X2ZvdW5kIG9m
#    ZjsKICAgICAgICAgICAgICAgIGFjY2Vzc19sb2cgb2ZmOwogICAgICAgIH0KCiAgICAgICAgbG9j
#    YXRpb24gLyB7CiAgICAgICAgICAgICAgICAjIFRoaXMgaXMgY29vbCBiZWNhdXNlIG5vIHBocCBp
#    cyB0b3VjaGVkIGZvciBzdGF0aWMgY29udGVudC4KICAgICAgICAgICAgICAgICMgaW5jbHVkZSB0
#    aGUgIj8kYXJncyIgcGFydCBzbyBub24tZGVmYXVsdCBwZXJtYWxpbmtzIGRvZXNuJ3QgYnJlYWsg
#    d2hlbiB1c2luZyBxdWVyeSBzdHJpbmcKICAgICAgICAgICAgICAgIHRyeV9maWxlcyAkdXJpICR1
#    cmkvIC9pbmRleC5waHA/JGFyZ3M7CiAgICAgICAgfQoKICAgICAgICBsb2NhdGlvbiB+IFwucGhw
#    JCB7CiAgICAgICAgICAgICAgICAjTk9URTogWW91IHNob3VsZCBoYXZlICJjZ2kuZml4X3BhdGhp
#    bmZvID0gMDsiIGluIHBocC5pbmkKICAgICAgICAgICAgICAgIGluY2x1ZGUgZmFzdGNnaV9wYXJh
#    bXM7CiAgICAgICAgICAgICAgICBmYXN0Y2dpX2ludGVyY2VwdF9lcnJvcnMgb247CiAgICAgICAg
#    ICAgICAgICBmYXN0Y2dpX3Bhc3MgcGhwOwogICAgICAgICAgICAgICAgI1RoZSBmb2xsb3dpbmcg
#    cGFyYW1ldGVyIGNhbiBiZSBhbHNvIGluY2x1ZGVkIGluIGZhc3RjZ2lfcGFyYW1zIGZpbGUKICAg
#    ICAgICAgICAgICAgIGZhc3RjZ2lfcGFyYW0gIFNDUklQVF9GSUxFTkFNRSAkZG9jdW1lbnRfcm9v
#    dCRmYXN0Y2dpX3NjcmlwdF9uYW1lOwogICAgICAgIH0KCiAgICAgICAgbG9jYXRpb24gfiogXC4o
#    anN8Y3NzfHBuZ3xqcGd8anBlZ3xnaWZ8aWNvKSQgewogICAgICAgICAgICAgICAgZXhwaXJlcyBt
#    YXg7CiAgICAgICAgICAgICAgICBsb2dfbm90X2ZvdW5kIG9mZjsKICAgICAgICB9Cn0K    
#
#- path: /srv/salt/database/init.sls
#  defer: true
#  permissions: "0644"
#  owner: salt:salt
#  content: |
#    db:
#      pkg.installed:
#      - name: mariadb
#      - pkgs:
#        - mariadb-server
#        - python3-pip
#      - refresh: true
#    
#      service.running:
#      - name: mariadb
#      - require:
#        - pkg: mariadb
#    
#      pip.installed:
#      - name: pymysql
#    
#      file.replace:
#      - name: "/etc/mysql/mariadb.conf.d/50-server.cnf"
#      - pattern: "bind-address.*"
#      - repl: "bind-address = 0.0.0.0"
#      - watch_in:
#        - service: mariadb
#    
#      mysql_database.present:
#      - name: "{{ pillar['wp_db_name'] }}"
#    
#      mysql_user.present:
#      - name: "{{ pillar['wp_db_user'] }}"
#      - host: "192.168.0.0/255.255.0.0"
#      - password: "{{ pillar['wp_db_pass'] }}"
#    
#      mysql_grants.present:
#      - grant: "all privileges"
#      - database: "{{ pillar['wp_db_user'] }}.*"
#      - user: "{{ pillar['wp_db_user'] }}"
#      - host: "192.168.0.0/255.255.0.0"
#
#- path: /srv/salt/wordpress/wp-config.php
#  defer: true
#  permissions: "0644"
#  owner: salt:salt
#  encoding: b64
#  content: >
#    PD9waHAgICAgICAgICAgICAgICAgICAgICAgCi8qKiAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgCiAqIFRoZSBiYXNlIGNvbmZpZ3VyYXRpb24gZm9yIFdvcmRQcmVzcwogKiAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAqIFRoZSB3cC1jb25maWcucGhwIGNy
#    ZWF0aW9uIHNjcmlwdCB1c2VzIHRoaXMgZmlsZSBkdXJpbmcgdGhlIGluc3RhbGxhdGlvbi4gICAg
#    ICAgICAgICAgICAgICAgCiAqIFlvdSBkb24ndCBoYXZlIHRvIHVzZSB0aGUgd2ViIHNpdGUsIHlv
#    dSBjYW4gY29weSB0aGlzIGZpbGUgdG8gIndwLWNvbmZpZy5waHAiCiAqIGFuZCBmaWxsIGluIHRo
#    ZSB2YWx1ZXMuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAKICoKICogVGhpcyBmaWxlIGNvbnRhaW5zIHRoZSBmb2xsb3dpbmcgY29uZmlndXJhdGlvbnM6
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICogICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAKICogKiBEYXRhYmFzZSBzZXR0aW5ncwogKiAqIFNlY3JldCBrZXlzCiAqICog
#    RGF0YWJhc2UgdGFibGUgcHJlZml4ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAqICogQUJTUEFUSCAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgCiAqICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAq
#    IEBsaW5rIGh0dHBzOi8vd29yZHByZXNzLm9yZy9kb2N1bWVudGF0aW9uL2FydGljbGUvZWRpdGlu
#    Zy13cC1jb25maWctcGhwLwogKiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAog
#    KiBAcGFja2FnZSBXb3JkUHJlc3MgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogKi8gICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    IAovLyAqKiBEYXRhYmFzZSBzZXR0aW5ncyAtIFlvdSBjYW4gZ2V0IHRoaXMgaW5mbyBmcm9tIHlv
#    dXIgd2ViIGhvc3QgKiogLy8KLyoqIFRoZSBuYW1lIG9mIHRoZSBkYXRhYmFzZSBmb3IgV29yZFBy
#    ZXNzICovICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
#    ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApkZWZpbmUoICdEQl9OQU1FJywg
#    J3t7IHBpbGxhclsnd3BfZGJfbmFtZSddIH19JyApOwoKLyoqIERhdGFiYXNlIHVzZXJuYW1lICov
#    CmRlZmluZSggJ0RCX1VTRVInLCAne3sgcGlsbGFyWyd3cF9kYl91c2VyJ10gfX0nICk7CgovKiog
#    RGF0YWJhc2UgcGFzc3dvcmQgKi8KZGVmaW5lKCAnREJfUEFTU1dPUkQnLCAne3sgcGlsbGFyWyd3
#    cF9kYl9wYXNzJ10gfX0nICk7Cgp7JSBzZXQgZGJfaXAgPSBzYWx0WydtaW5lLmdldCddKHRndD0n
#    ZGIwJywgZnVuPSduZXR3b3JrLmlwX2FkZHJzJykgLSV9Ci8qKiBEYXRhYmFzZSBob3N0bmFtZSAq
#    LwpkZWZpbmUoICdEQl9IT1NUJywgJ3t7IGRiX2lwWydkYjAnXVswXSB9fScgKTsKCi8qKiBEYXRh
#    YmFzZSBjaGFyc2V0IHRvIHVzZSBpbiBjcmVhdGluZyBkYXRhYmFzZSB0YWJsZXMuICovCmRlZmlu
#    ZSggJ0RCX0NIQVJTRVQnLCAndXRmOCcgKTsKCi8qKiBUaGUgZGF0YWJhc2UgY29sbGF0ZSB0eXBl
#    LiBEb24ndCBjaGFuZ2UgdGhpcyBpZiBpbiBkb3VidC4gKi8KZGVmaW5lKCAnREJfQ09MTEFURScs
#    ICcnICk7CgovKiojQCsKICogQXV0aGVudGljYXRpb24gdW5pcXVlIGtleXMgYW5kIHNhbHRzLgog
#    KgogKiBDaGFuZ2UgdGhlc2UgdG8gZGlmZmVyZW50IHVuaXF1ZSBwaHJhc2VzISBZb3UgY2FuIGdl
#    bmVyYXRlIHRoZXNlIHVzaW5nCiAqIHRoZSB7QGxpbmsgaHR0cHM6Ly9hcGkud29yZHByZXNzLm9y
#    Zy9zZWNyZXQta2V5LzEuMS9zYWx0LyBXb3JkUHJlc3Mub3JnIHNlY3JldC1rZXkgc2VydmljZX0u
#    IAogKgogKiBZb3UgY2FuIGNoYW5nZSB0aGVzZSBhdCBhbnkgcG9pbnQgaW4gdGltZSB0byBpbnZh
#    bGlkYXRlIGFsbCBleGlzdGluZyBjb29raWVzLgogKiBUaGlzIHdpbGwgZm9yY2UgYWxsIHVzZXJz
#    IHRvIGhhdmUgdG8gbG9nIGluIGFnYWluLgogKgogKiBAc2luY2UgMi42LjAKICovCmRlZmluZSgg
#    J0FVVEhfS0VZJywgICAgICAgICAncHV0IHlvdXIgdW5pcXVlIHBocmFzZSBoZXJlJyApOwpkZWZp
#    bmUoICdTRUNVUkVfQVVUSF9LRVknLCAgJ3B1dCB5b3VyIHVuaXF1ZSBwaHJhc2UgaGVyZScgKTsK
#    ZGVmaW5lKCAnTE9HR0VEX0lOX0tFWScsICAgICdwdXQgeW91ciB1bmlxdWUgcGhyYXNlIGhlcmUn
#    ICk7CmRlZmluZSggJ05PTkNFX0tFWScsICAgICAgICAncHV0IHlvdXIgdW5pcXVlIHBocmFzZSBo
#    ZXJlJyApOwpkZWZpbmUoICdBVVRIX1NBTFQnLCAgICAgICAgJ3B1dCB5b3VyIHVuaXF1ZSBwaHJh
#    c2UgaGVyZScgKTsKZGVmaW5lKCAnU0VDVVJFX0FVVEhfU0FMVCcsICdwdXQgeW91ciB1bmlxdWUg
#    cGhyYXNlIGhlcmUnICk7CmRlZmluZSggJ0xPR0dFRF9JTl9TQUxUJywgICAncHV0IHlvdXIgdW5p
#    cXVlIHBocmFzZSBoZXJlJyApOwpkZWZpbmUoICdOT05DRV9TQUxUJywgICAgICAgJ3B1dCB5b3Vy
#    IHVuaXF1ZSBwaHJhc2UgaGVyZScgKTsKCi8qKiNALSovCgovKioKICogV29yZFByZXNzIGRhdGFi
#    YXNlIHRhYmxlIHByZWZpeC4KICoKICogWW91IGNhbiBoYXZlIG11bHRpcGxlIGluc3RhbGxhdGlv
#    bnMgaW4gb25lIGRhdGFiYXNlIGlmIHlvdSBnaXZlIGVhY2gKICogYSB1bmlxdWUgcHJlZml4LiBP
#    bmx5IG51bWJlcnMsIGxldHRlcnMsIGFuZCB1bmRlcnNjb3JlcyBwbGVhc2UhCiAqLwokdGFibGVf
#    cHJlZml4ID0gJ3dwXyc7CgovKioKICogRm9yIGRldmVsb3BlcnM6IFdvcmRQcmVzcyBkZWJ1Z2dp
#    bmcgbW9kZS4KICoKICogQ2hhbmdlIHRoaXMgdG8gdHJ1ZSB0byBlbmFibGUgdGhlIGRpc3BsYXkg
#    b2Ygbm90aWNlcyBkdXJpbmcgZGV2ZWxvcG1lbnQuCiAqIEl0IGlzIHN0cm9uZ2x5IHJlY29tbWVu
#    ZGVkIHRoYXQgcGx1Z2luIGFuZCB0aGVtZSBkZXZlbG9wZXJzIHVzZSBXUF9ERUJVRwogKiBpbiB0
#    aGVpciBkZXZlbG9wbWVudCBlbnZpcm9ubWVudHMuCiAqCiAqIEZvciBpbmZvcm1hdGlvbiBvbiBv
#    dGhlciBjb25zdGFudHMgdGhhdCBjYW4gYmUgdXNlZCBmb3IgZGVidWdnaW5nLAogKiB2aXNpdCB0
#    aGUgZG9jdW1lbnRhdGlvbi4KICoKICogQGxpbmsgaHR0cHM6Ly93b3JkcHJlc3Mub3JnL2RvY3Vt
#    ZW50YXRpb24vYXJ0aWNsZS9kZWJ1Z2dpbmctaW4td29yZHByZXNzLwogKi8KZGVmaW5lKCAnV1Bf
#    REVCVUcnLCBmYWxzZSApOwoKLyogQWRkIGFueSBjdXN0b20gdmFsdWVzIGJldHdlZW4gdGhpcyBs
#    aW5lIGFuZCB0aGUgInN0b3AgZWRpdGluZyIgbGluZS4gKi8KCgoKLyogVGhhdCdzIGFsbCwgc3Rv
#    cCBlZGl0aW5nISBIYXBweSBwdWJsaXNoaW5nLiAqLwoKLyoqIEFic29sdXRlIHBhdGggdG8gdGhl
#    IFdvcmRQcmVzcyBkaXJlY3RvcnkuICovCmlmICggISBkZWZpbmVkKCAnQUJTUEFUSCcgKSApIHsK
#    ICAgICAgICBkZWZpbmUoICdBQlNQQVRIJywgX19ESVJfXyAuICcvJyApOwp9CgovKiogU2V0cyB1
#    cCBXb3JkUHJlc3MgdmFycyBhbmQgaW5jbHVkZWQgZmlsZXMuICovCnJlcXVpcmVfb25jZSBBQlNQ
#    QVRIIC4gJ3dwLXNldHRpbmdzLnBocCc7Cg==
#
#- path: /srv/pillar/mysql.sls
#  defer: true
#  permissions: "0644"
#  owner: salt:salt
#  content: |
#    wp_db_name: "wordpress"
#    wp_db_user: "wordpress"
#    wp_db_pass: "wordpresspassword"
#
#- path: /srv/pillar/top.sls
#  defer: true
#  permissions: "0644"
#  owner: salt:salt
#  content: |
#    base:
#      'app*':
#      - mysql
#      'db*':
#      - mysql
